[package]
name = "pikav-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
awc = "3.0.0"
serde = "1.0.81"
serde_json = "1.0.81"
parking_lot = "0.12.1"
actix-rt = "2.7.0"
tracing = "0.1.35"