[package]
name = "example"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pikav-api = { path = "../api" }
pikav-client = { path = "../client" }

actix-web = "4.0.1"
serde = { version = "1.0.81", features = ["derive"] }
serde_json = "1.0.81"
rbatis = "3.1.11"
rbson = "2.0.3"
rand = "0.8.5"