branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - verifyConditionsCmd: "semantic-release-rust verify-conditions"
      prepareCmd: "semantic-release-rust prepare ${nextRelease.version}"
  - - "@semantic-release/exec"
      prepareCmd: "cargo build --release"
  - - "@codedependant/semantic-release-docker"
    - dockerProject: "timada0"
      dockerImage: "pikav"
  - - "@semantic-release/git"
    - assets: Cargo.toml
