branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - path: "@codedependant/semantic-release-docker"
    dockerProject: "timada0"
    dockerImage: "pikav"
