[package]
name = "pikav"
version ="1.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0"

[workspace]
members = [
    "example"
]
