version: "3.9"

services:
  pulsar:
    image: apachepulsar/pulsar:2.9.1
    volumes:
      - pulsar-data:/pulsar/data
      - pulsar-conf:/pulsar/conf
    ports:
      - "6650:6650"
    command: bin/pulsar standalone

  pulsar-init:
    image: apachepulsar/pulsar:2.9.1
    volumes:
      - ./.docker/pulsar/client.conf:/pulsar/conf/client.conf
      - ./.docker/pulsar/init-data.sh:/init-data.sh
    command: /init-data.sh
    depends_on:
      - pulsar
    restart: on-failure

  cockroach:
    image: cockroachdb/cockroach:v21.2.6
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    ports:
      - "26257:26257"
    command: start-single-node --insecure

  kratos-migrate:
    image: oryd/kratos:v0.9.0-alpha.3
    environment:
      - DSN=cockroach://root@cockroach:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./.docker/ory/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.9.0-alpha.3
    environment:
      - PORT=4435
      - SECURITY_MODE=jwks
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4455/.ory/kratos/public
    restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.9.0-alpha.3
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=cockroach://root@cockroach:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./.docker/ory/kratos/email-password
        target: /etc/config/kratos

  oathkeeper:
    image: oryd/oathkeeper:v0.38.25-beta.1
    depends_on:
      - kratos
    ports:
      - 4455:4455
      - 4456:4456
    command:
      serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    volumes:
      - ./.docker/ory/oathkeeper:/etc/config/oathkeeper
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  keto:
    image: oryd/keto:v0.8.0-alpha.2
    ports:
      - '4466:4466'
      - '4467:4467'
    command: serve
    environment:
      - LOG_LEVEL=debug
      - PORT=4466
      - DSN=cockroach://root@cockroach:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: on-failure

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'

volumes:
  pulsar-data:
  pulsar-conf:
  cockroach-data:
