version: "3.9"

services:
  kratos-migrate:
    image: oryd/kratos:v0.9.0-alpha.3
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./.docker/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.9.0-alpha.3
    environment:
      - PORT=4435
      - SECURITY_MODE=jwks
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4455/.ory/kratos/public
    restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.9.0-alpha.3
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./.docker/kratos/email-password
        target: /etc/config/kratos

  oathkeeper:
    image: oryd/oathkeeper:v0.38.25-beta.1
    depends_on:
      - kratos
    ports:
      - 4455:4455
      - 4456:4456
    command:
      serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    volumes:
      - ./.docker/oathkeeper:/etc/config/oathkeeper
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  keto:
    image: oryd/keto:v0.8.0-alpha.2
    ports:
      - '4466:4466'
      - '4467:4467'
    command: serve
    environment:
      - LOG_LEVEL=debug
      - PORT=4466
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    restart: on-failure
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: .docker/keto/keto.yml
        target: /home/ory/keto.yml

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'

volumes:
  kratos-sqlite:
