[package]
name = "pikav"
version ="0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
thiserror = "1.0.31"
regex = "1.5.6"
parking_lot = "0.12.1"
tokio = { version = "1.19.0", features = ["full"] }
nanoid = "0.4.0"
serde = "1.0.81"
serde_json = "1.0.81"
