addr: ":6751"

jwks_url: http://127.0.0.1:4456/.well-known/jwks.json

zone: eu-west-1b

nodes:
  - url: http://127.0.0.1:6750
    zone: eu-west-1a
    shared: true
  - url: http://127.0.0.1:6752
    zone: eu-west-1c
    shared: true
  - url: http://127.0.0.1:6753
    zone: us-west-1a
