addr: ":6752"

jwks_url: http://127.0.0.1:4456/.well-known/jwks.json

zone: eu-west-1c

nodes:
  - url: http://127.0.0.1:6750
    zone: eu-west-1a
    shared: true
  - url: http://127.0.0.1:6751
    zone: eu-west-1b
    shared: true
  - url: http://127.0.0.1:6753
    zone: us-west-1a
