id: pikav-${PIKAV_APP_ID|default}-${PIKAV_ZONE|eu-west-1a}
addr: ${PIKAV_ADDR|:6750}

jwks_url: ${PIKAV_JWKS_URL|http://127.0.0.1:4456/.well-known/jwks.json}

broker:
  url: ${PIKAV_BROKER_URL|pulsar://localhost:6650}
  topic: non-persistent://timada/pikav/${PIKAV_APP_ID|default}
