[package]
name = "pikav-api"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pikav = { path = "../pikav" }
pikav-client = { path = "../client" }

actix-web = "4.0.1"
actix-cors = "0.6.1"
serde = "1.0.81"
serde_json = "1.0.81"
futures-core = "0.3.21"
futures-util = "0.3.21"
thiserror = "1.0.31"
josekit = "0.8.0"
parking_lot = "0.12.1"
awc = "3.0.0"
tracing = "0.1.35"
lazy_static = "1.4.0"
