name: Release
on:
  push:
    branches:
      - main

jobs:
  go:
    uses: timada-org/.github/.github/workflows/go-release.yml@perf/go-docker-build
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
